AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sestrel-webhook

  Sample SAM Template for sestrel-webhook
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WebhookHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: webhook/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        ExpoBuildFinished:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: get
      Environment:
        Variables:
          EXPO_WEBHOOK_SECRET: aqwxszedcvfrtgbn
